<?php
declare(strict_types=1);

require_once __DIR__ . '/includes/config.php';
require_once __DIR__ . '/includes/security.php';
require_once __DIR__ . '/includes/ai-brief.php';

header('Content-Type: application/json; charset=utf-8');
header('X-Content-Type-Options: nosniff');

$corsOrigin = contact_cors_origin();
if ($corsOrigin !== '') {
    header('Access-Control-Allow-Origin: ' . $corsOrigin);
    header('Vary: Origin');
}
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(204);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['error' => 'Method Not Allowed']);
    exit;
}

$input = json_decode(file_get_contents('php://input') ?: '', true);
if (!is_array($input)) {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid JSON']);
    exit;
}

if (!empty($input['website'] ?? '')) {
    echo json_encode(['type' => 'OK', 'timelineStr' => '—', 'source' => 'template']);
    exit;
}

// Tighter than before: each request may hit a paid AI API.
if (!rate_limit_allow('estimate_wizard', 20, 3600)) {
    http_response_code(429);
    echo json_encode(['error' => 'Too many requests. Please try again in a few minutes.']);
    exit;
}

$n = ai_brief_normalize_input($input);

if ($n['name'] === '' || $n['email'] === '' || !filter_var($n['email'], FILTER_VALIDATE_EMAIL)) {
    http_response_code(400);
    echo json_encode(['error' => 'Name and a valid email are required']);
    exit;
}

if ($n['type'] === '' || $n['scale'] === '') {
    http_response_code(400);
    echo json_encode(['error' => 'Please select a project type and scale']);
    exit;
}

$brief = ai_brief_generate($n);
$source = $brief !== null ? 'ai' : 'template';
$brief ??= ai_brief_template($n);

$clientLine = $n['name'] . ($n['company'] !== '' ? ' · ' . $n['company'] : '');

$briefText = "PROJECT BRIEF — {$n['type']} ({$n['scale']} scale)\n"
    . "Client: {$clientLine}\n\n"
    . "{$brief['summary']}\n\n"
    . "--- SCOPE ---\n{$brief['scope']}\n\n"
    . "--- TECH STACK ---\n{$brief['tech']}\n\n"
    . "--- ASSUMPTIONS & NOTES ---\n{$brief['notes']}\n\n"
    . "--- INDICATIVE TIMELINE ---\n{$brief['timelineStr']} · Complexity: {$brief['complexity']}\n\n"
    . "(Generated by the Dashandots AI scoping assistant. Pricing to follow in our proposal.)";

echo json_encode([
    'type'        => $n['type'],
    'clientName'  => $clientLine,
    'timelineStr' => $brief['timelineStr'],
    'complexity'  => $brief['complexity'],
    'summary'     => $brief['summary'],
    'scope'       => $brief['scope'],
    'tech'        => $brief['tech'],
    'notes'       => $brief['notes'],
    'briefText'   => $briefText,
    'source'      => $source,
], JSON_UNESCAPED_UNICODE);
